# Generated by Django 3.2.25 on 2024-06-27 04:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0009_employee_employee_blood_group_employee_comment_employee_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_comment',
            name='date',
            field=models.DateField(default=datetime.date(2024, 6, 27)),
        ),
    ]
